### ISSUE TITLE
Broken pattern conversion: 'Uncaught HierarchyRequestError'

### ISSUE THREAD

**Issue by tian2992** [fashiontec/knitweb#11]
When running the editor on the Github pages. I add 3 yarn colors and click generate. The generated pattern is all black and has 3 HierarchyRequestError on the developer console.

**Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.**

```
function addButtonClick(hex){
    ...
    newCell.appendChild(newCell);
```

**Comment by sameeragunarathne** [comment]
HierarchyRequestError comes because of a library used for colour picker. It's not causing for broken pattern generation. I have updated the event flow of the pattern generator. should look and test it's working now.
