### ISSUE TITLE
REST client for accessing REST api methods

### ISSUE THREAD

**Issue by sameeragunarathne** [fashiontec/knitweb#15]
This issue is to keep track of REST client implementation for accessing REST api methods exposed at the server side. In the initial step creating a user and authenticating a user for a user name and a password combination is implemented.

**Comment by sameeragunarathne** [comment]
TODO: JSON parser implementation for REST client.

**Comment by tian2992** [comment]
I am not sure if User-Password auth is the best choice for pairing. Mostly taking into account that some installs can be headless and will be mostly within local networks, is there enough potential for abuse such as we need to have password auth? cc // @mariobehling

**Comment by sameeragunarathne** [comment]
Yes user-password based scheme may be problematic to use. Is there any better suggestion for session management used for knitweb ?

**Comment by sameeragunarathne** [comment]
Implementation and configuration of essential client methods are completed. Implementation is at https://github.com/fashiontec/knitweb/blob/master/app/model/client/client.js
