### ISSUE TITLE
Reduce Noise of the generated pixelated pattern

### ISSUE THREAD

**Issue by sameeragunarathne** [fashiontec/knitweb#5]
There is a issue of getting a noisy pixels inside the newly generated pixel grid because of the round up process. In this issue I would like to discuss what are the steps can take to reduce the noise from the patterns.

**Comment by tian2992** [comment]
Maybe applying some kind of dithering?
http://www.tannerhelland.com/4660/dithering-eleven-algorithms-source-code/

**Comment by sameeragunarathne** [comment]
The current psedocode for the pixelating algo is as follow.
1. Loading image into a canvas element
2. Formulate a grid for the canvas (size:num of stitches per row*num of rows).Save average rgb value for a grid cell inside a array.
3. Compare the euclidean distance of a average colour of a cell with the available yarn colours. Available yarn colours should insert by the user with the loading of the image. (Nearest neighbour algo)
4. Select the lowest distanced colour from the available colour set and redraw cells accordingly.

Reconstructed Pattern with the available yarn colours
![screenshot from 2015-06-15 21 33 30](https://cloud.githubusercontent.com/assets/5234677/8166264/51d8af5e-13b4-11e5-9934-39f2a09c8ead.png)
